/*
 * ABM de Usuarios
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
)

type Usuario struct {
	Documento string `json:"documento,omitempty"`

	Username string `json:"username,omitempty"`

	Nombres string `json:"nombres,omitempty"`

	Apellidos string `json:"apellidos,omitempty"`

	Genero string `json:"genero,omitempty"`

	FechaNacimiento string `json:"fechaNacimiento,omitempty"`
}

func crearUsuario(_document, _username, _nombres, _apellidos, _genero, _fechaNacimiento string) Usuario {
	usuario := Usuario{
		Documento:       _document,
		Username:        _username,
		Nombres:         _nombres,
		Apellidos:       _apellidos,
		Genero:          _genero,
		FechaNacimiento: _fechaNacimiento,
	}

	return usuario
}

func toJson(usuario *Usuario) string {
	e, _ := json.Marshal(usuario)
	return string(e)
}
